### ISSUE TITLE
how to use fx-progress-circle

### ISSUE THREAD

**Issue by olaLH** [torakiki/fx-progress-circle#1]
Hi 
this the code that i write it.

RingProgressIndicator ringCircleIndicator=new RingProgressIndicator();
ringCircleIndicator.setProgress(30);
String css = this.getClass().getResource("circleIndicator.css").toExternalForm();
ringCircleIndicator.getStylesheets().add(css);

but the style is changed only the color of circle & not fill the gap between two circles according to progress value.
thanks

**Comment by torakiki** [comment]
It should work now, I also added a couple of example classes
